### PR TITLE
Add engagements service

### PR DESCRIPTION
**Pull request by kevin830222**
I follow your rules to implement all the engagements part, including:

+ create
+ update
+ delete 
+ get 
+ associate

Reference for: http://developers.hubspot.com/docs

### CODE REVIEW

**Comment by ryanwinchester** [comment]
Sorry, this is hte first time I used Nitpick CI. It seems to be very picky!

**Comment by ryanwinchester** [comment]
Thanks!

**Comment by kevin830222** [comment]
i try hard to fix the style issue but no work. lol

**Comment by kevin830222** [comment]
one more question, why not develop on `develop` branch to follow git flow?
I seldom see the commit on `master` branch is newer than the `develop` branch

**Comment by ryanwinchester** [comment]
it's not at 1.0 yet, so it's just assumed it's not stable and could have breaking changes

**Pull request merged**
