### PR TITLE
Fixed the baseUrl property and added default value for Api::request

### PR DESCRIPTION
**Pull request by fyfey**
Base URL was still broken in this branch and request was moaning about required 3rd parameter so I re-added the default empty array back in

### CODE REVIEW

**Comment by ryanwinchester** [comment]
:+1:

**Comment by fyfey** [comment]
This commit doesn't seem to have propagated to packagist, is this a manual process?

**Comment by ryanwinchester** [comment]
odd... it should.

you're using branch `dev-php53`?

**Comment by ryanwinchester** [comment]
i refreshed the packagist credentials

**Pull request merged**
