### PR TITLE
add method argument in update engagement

### PR DESCRIPTION
**Pull request by iveto89**
Add `method` argument in `update` engagement in order to use `patch` instead of `put`.

https://developers.hubspot.com/docs/methods/engagements/update_engagement-patch

### CODE REVIEW

**Comment by ryanwinchester** [comment]
Do they only document `PATCH` for this endpoint?

Reading the docs, I think maybe we should make it default to that?

You could say it's *technically* a breaking change, but it's probably more like a bugfix, in my opinion.

**Comment by iveto89** [comment]
There is also `put` method in the docs:
https://developers.hubspot.com/docs/methods/engagements/update_engagement
That's why I made it default to `put`.

**Comment by jamesgraham** [comment]
@ryanwinchester the endpoint supports `PUT` and `PATCH` - they do different things so I think we need to support both.

**Comment by ryanwinchester** [comment]
@jamesgraham Yes, but I was recommending making `PATCH` the _default_.

**Comment by iveto89** [comment]
@ryanwinchester I've made `patch` default.

**Comment by dinamic** [comment]
Using `PATCH` sounds logical to me. Maybe it would make sense to also have a `replace()` implementation that would use the `PUT` method.

Could we have this one merged and tagged, @ryanwinchester?
Thanks!

**Pull request merged**
