### PR TITLE
Preventing form submission to send API key details

### PR DESCRIPTION
**Pull request by tjasko**
There's an issue when doing form submissions, it will send the API credentials as a query string, and HubSpot actually does not filter this out. This is a pretty big security risk, so I figured I'd help out and fix it.

### CODE REVIEW

**Comment by ryanwinchester** [comment]
Thanks.

Can you explain why this is a big security risk?

**Comment by tjasko** [comment]
The API key was saved with the contact parameters, HubSpot doesn't filter it and when I was viewing the contact in their UI, I could see the API key in plain text as a property.

It's definitely something HubSpot _shoud_ be filtering because I'm sure people do it accidently, but yeah, it startled me when I saw it.

**Comment by ryanwinchester** [comment]
LOL

yeah, good to know

**Comment by tjasko** [comment]
Well for one this would let anyone who has read-only access to HubSpot get
your API key. Not only that, who knows what integrations people have hooked
into HubSpot. This is all of course usually internal anyways, but it's not
something you want in plain text. There are plenty of ways I can imagine of
the key getting in the wrong hands. It's an API key, it's not something
that should be exposed. :)

**Pull request merged**
